#!/usr/bin/env bash

generate_rclone_filter() {
  local include_file="$1"
  local exclude_file="$2"
  local out_file="$3"
  local exclude_extra_file="${4:-}"
  local tmp_file
  tmp_file="$(mktemp)"

  _filter_clean_lines() {
    awk 'NF && $0 !~ /^[[:space:]]*#/' "$1"
  }

  _emit_parent_dirs() {
    local path="$1"
    local rel="${path#/}"
    local current=""
    local IFS='/'
    local parts=()
    read -r -a parts <<< "$rel"
    if [[ ${#parts[@]} -le 1 ]]; then
      return
    fi
    local last_index=$((${#parts[@]} - 1))
    local i=0
    while [[ $i -lt $last_index ]]; do
      current="${current}/${parts[$i]}"
      printf '+ %s/\n' "$current" >> "$tmp_file"
      i=$((i + 1))
    done
  }

  : > "$tmp_file"

  {
    echo "# Generated by macback"
    echo
    echo "# Excludes"
    _filter_clean_lines "$exclude_file" | while IFS= read -r line; do
      printf -- '- %s\n' "$line"
    done
    if [[ -n "$exclude_extra_file" && -f "$exclude_extra_file" ]]; then
      _filter_clean_lines "$exclude_extra_file" | while IFS= read -r line; do
        printf -- '- %s\n' "$line"
      done
    fi
    echo
    echo "# Includes"
  } > "$tmp_file"

  _filter_clean_lines "$include_file" | while IFS= read -r path; do
    if [[ "$path" == */\*\* ]]; then
      local base="${path%/**}"
      _emit_parent_dirs "$base"
      printf '+ %s/\n' "$base" >> "$tmp_file"
      printf '+ %s\n' "$path" >> "$tmp_file"
    elif [[ "$path" == */ ]]; then
      local base="${path%/}"
      _emit_parent_dirs "$base"
      printf '+ %s/\n' "$base" >> "$tmp_file"
    else
      _emit_parent_dirs "$path"
      printf '+ %s\n' "$path" >> "$tmp_file"
    fi
  done

  {
    echo
    echo "# Drop everything else"
    echo "- **"
  } >> "$tmp_file"

  awk '!seen[$0]++' "$tmp_file" > "$out_file"
  rm -f "$tmp_file"
}
